function data = ReadSPRFile(pfname)
% ReadSPRFile - reads in spr file generated by fit2d
%
%   USAGE:
%
%   data = ReadSPRFile(pfname)
%
%   INPUT:
%
%   pfname
%       full file name of the spr file
%
%   OUTPUT:
%   
%   data
%       extracted spr data in a matrix form
%
%   pfname
%       full file name of the spr file
%

data    = [];
fid_spr = fopen(pfname, 'r');
while ~feof(fid_spr)
    lindata = fgetl(fid_spr);
    if isempty(strfind(lindata, 'Start pixel'))
        data    = [data; str2num(lindata)];
    end
end
fclose(fid_spr);