function pts_out = FiberTube(pts_in, deta, dome)
deta_stretch    = deta/0.5;
dome_stretch    = dome/0.5;
stretch         = sqrt(2)*deta_stretch*dome_stretch/sqrt(deta_stretch*deta_stretch + dome_stretch*dome_stretch);

[TH,PHI,~]  = cart2sph(pts_in(1,1),pts_in(2,1),pts_in(3,1));

V1  = deg2rad(0.5);
V2  = deg2rad(0.5)*cosd(45);

THpts   = [ ...
    TH+V1*dome_stretch; ...
    TH+V2*stretch; ...
    TH; ...
    TH-V2*stretch; ...
    TH-V1*dome_stretch; ...
    TH-V2*stretch; ...
    TH; ...
    TH+V2*stretch; ...
    ];
PHIpts  = [ ...
    PHI; ...
    PHI+V2*stretch; ...
    PHI+V1*deta_stretch; ...
    PHI+V2*stretch; ...
    PHI; ...
    PHI-V2*stretch; ...
    PHI-V1*deta_stretch; ...
    PHI-V2*stretch; ...
    ];
Rpts    = ones(size(THpts));

[x, y, z]   = sph2cart(THpts,PHIpts,Rpts);
pts_out     = [pts_in [x y z]'];
pts_out     = UnitVector(pts_out);