function w = FiberTubeWeight(deta, dome)
% clear all
% close all
% clc
% 
% deta    = 5/2;
% dome    = 10/2;

deta_stretch    = deta/0.5;
dome_stretch    = dome/0.5;
stretch         = sqrt(2)*deta_stretch*dome_stretch/sqrt(deta_stretch*deta_stretch + dome_stretch*dome_stretch);

pts         = [1 0 0]';
[TH,PHI,~]  = cart2sph(pts(1,1),pts(2,1),pts(3,1));

V1  = deg2rad(0.5);
V2  = deg2rad(0.5)*cosd(45);

THpts   = [ ...
    TH+V1*dome_stretch; ...
    TH+V2*stretch; ...
    TH; ...
    TH-V2*stretch; ...
    TH-V1*dome_stretch; ...
    TH-V2*stretch; ...
    TH; ...
    TH+V2*stretch; ...
    ];
PHIpts  = [ ...
    PHI; ...
    PHI+V2*stretch; ...
    PHI+V1*deta_stretch; ...
    PHI+V2*stretch; ...
    PHI; ...
    PHI-V2*stretch; ...
    PHI-V1*deta_stretch; ...
    PHI-V2*stretch; ...
    ];
Rpts    = ones(size(THpts));

[x, y, z]   = sph2cart(THpts,PHIpts,Rpts);
pts         = [pts [x y z]'];
pts         = UnitVector(pts);

% plot3(pts(1,:), pts(2,:), pts(3,:), 'k.')
% axis equal
% hold on

sph.crd = pts;
sph.con = [1 2 3; 1 3 4; 1 4 5; 1 5 6; 1 6 7; 1 7 8; 1 8 9; 1 9 2]';
sph.eqv = [];
qrule2d = LoadQuadrature('qr_trid06p12');
[~, sph.l2ip]   = SphGQRule(sph, qrule2d);
w   = sum(sph.l2ip)./sum(sum(sph.l2ip));