%MEXCOMMAND Make mca.dll and timereval.dll
%
% From ben.shepherd@stfc.ac.uk, Fri Jun 13 2014

cd ('C:\Program Files\MATLAB\R2014a\toolbox\mca')

mex mca.cpp MCAError.cpp Channel.cpp ...
            C:\epics\base\lib\windows-x64\Com.lib ...
            C:\epics\base\lib\windows-x64\ca.lib ...
            -DDB_TEXT_GLBLSOURCE -DMSCC -DEPICS_DLL_NO ...
            -DWIN64 -DWIN32 ...
            -IC:\epics\base\include ...
            -IC:\epics\base\include\os\WIN32 ...
            -v

mex timereval.cpp -v -DWIN32
