clear all
close all
clc

addpath(genpath('/home/beams/PARKJS/matlab/matlab_tools'));
% addpath(genpath('C:\Users\parkjs\Documents\GitHub\matlab_tools'));

%%% CALIBRATION FILES
XRDIMAGE.Calib.pname        = '/home/beams/S1IDUSER/mnt/orthros/mpe1_oct20_bc';
XRDIMAGE.Calib.froot        = 'LaB6_1s';
XRDIMAGE.Calib.fnumber      = 6:7; % 4116 / 4117
XRDIMAGE.Calib.numdigs      = 6;
XRDIMAGE.Calib.fext         = 'ge3';
XRDIMAGE.Calib.corrected    = 'sum';

%%% SAMPLE FILES
XRDIMAGE.Image.pname        = '/home/beams/S1IDUSER/mnt/orthros/mpe1_oct20_bc';
XRDIMAGE.Image.numdigs      = 6;
XRDIMAGE.Image.fext         = 'ge3';        %%% CHECK METADATA SEARCH
XRDIMAGE.Image.corrected    = 'cor32';
XRDIMAGE.Image.IsHydra      = 0;    % 0 = Single panel; 1 = GE1; 2 = GE2; 3 = GE3; 4 = GE4;

%%% METADATA FILES
XRDIMAGE.Image.per_scan_metadata    = '/home/beams/S1IDUSER/new_data/mpe1_oct20/saxs_waxs_fmt_fastpar.par';
XRDIMAGE.Image.per_frame_metadata   = '/home/beams/S1IDUSER/new_data/mpe1_oct20/mpe1_oct20_FF.par';

XRDIMAGE.Image.samplename   = 'hassani_sam1';
FROOT   = {'hassani_sam1_load0_pd'; ...
    'hassani_sam1_load02_pd'; ...
    'hassani_sam1_load04_pd'; ...
    'hassani_sam1_load06_pd'; ...
    'hassani_sam1_load08_pd'; ...
    'hassani_sam1_load10_pd' ; ...
    'hassani_sam1_loadc1_pd' ; ...
    'hassani_sam1_loadc2_pd' ; ...
    'hassani_sam1_loadc3_pd' ; ...
    'hassani_sam1_loadc4_pd' ; ...
    'hassani_sam1_loadc5_pd' ; ...
    'hassani_sam1_loadc6_pd' ; ...
    'hassani_sam1_loadc7_pd' ; ...
    'hassani_sam1_loadc8_pd' ; ...
    'hassani_sam1_loadc9_pd' ; ...
    'hassani_sam1_loadc10_pd' ; ...
    'hassani_sam1_loadc11_pd' ; ...
    'hassani_sam1_loadc12_pd' ; ...
    'hassani_sam1_loadc13_pd' ; ...
    'hassani_sam1_loadc14_pd' ; ...
    'hassani_sam1_loadc15_pd' ; ...
    'hassani_sam1_loadc16_pd' ; ...
    'hassani_sam1_loadc17_pd' ; ...
    'hassani_sam1_loadc18_pd' ; ...
    'hassani_sam1_loadc19_pd' ; ...
    'hassani_sam1_loadc20_pd' ; ...
    'hassani_sam1_loadc21_pd' ; ...
    'hassani_sam1_loadc22_pd' ; ...
    'hassani_sam1_loadc23_pd' ; ...
    'hassani_sam1_loadc24_pd' ; ...
    'hassani_sam1_loadc25_pd' ; ...
    'hassani_sam1_loadc26_pd' ; ...
    'hassani_sam1_loadc27_pd' ; ...
    'hassani_sam1_loadc28_pd' ; ...
    'hassani_sam1_loadc29_pd' ; ...
    };

% XRDIMAGE.Image.samplename   = 'hassani_sam2';
% FROOT   = {'hassani_sam2_load00_pd'; ...
%     'hassani_sam2_load01_pd'; ...
%     'hassani_sam2_load02_pd'; ...
%     'hassani_sam2_load03_pd'; ...
%     'hassani_sam2_loadc01_pd'; ...
%     'hassani_sam2_loadc02_pd'; ...
%     'hassani_sam2_loadc03_pd'; ...
%     'hassani_sam2_loadc04_pd'; ...
%     'hassani_sam2_loadc05_pd'; ...
%     'hassani_sam2_loadc06_pd'; ...
%     'hassani_sam2_loadc07_pd'; ...
%     'hassani_sam2_loadc08_pd'; ...
%     'hassani_sam2_loadc09_pd'; ...
%     };

% FROOT{iiii}
proot   = '/home/beams/S1IDUSER/mnt/orthros/mpe1_oct20_bc';
% delete(gcp)
% parpool(3)
for iiii = 1:1:length(FROOT)
    %%% INPUT PARAMETERS
    pname   = fullfile(proot, XRDIMAGE.Image.samplename, XRDIMAGE.Image.fext, FROOT{iiii});
    cmd1    = sprintf('! mkdir %s', pname);
%     eval(cmd1)
%     
    cmd2    = sprintf('! mv -v %s_* %s', pname, pname);
%     eval(cmd2)
    cmd3    = sprintf('! ls -l %s | wc -l', pname)
    eval(cmd3)
    pause(2)
end
% delete(gcp)