clear all
close all
clc

%%% VARIOUS PATH NAMES
% PNAME_SOLUTION  = 'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example';	%%% SOLUTION PATH
PNAME_SOLUTION  = '/home/jspark/VBShared/residual-stress/multiscale-formulation/example';	%%% SOLUTION PATH

%%% INPUT FILE NAME - THIS IS THE FILE THAT GETS USED IN STEPS 0 TO 7
FNAME_INPUT = 'example_rsinput.mat';

%%% VARIOUS FILE NAMES
FNAME_A     = 'A.mat';          %%% A-MATRIX FILE NAME
FNAME_N     = 'N.mat';          %%% N-MATRIX FILE NAME
FNAME_L     = 'L.mat';          %%% L-MATRIX FILE NAME
FNAME_Nz    = 'Nz.mat';         %%% Nz-MATRIX FILE NAME - THIS IS REMNANTS OF KM'S IMPLEMENTATION
FNAME_Nxy	= 'Nxy.mat';        %%% Nxy-MATRIX FILE NAME - THIS IS REMNANTS OF KM'S IMPLEMENTATION
FNAME_Fvec  = 'Fvec.mat';       %%% Fvec-VECTOR FILE NAME
FNAME_LS	= 'LSALL.mat';      %%% LS-VECTOR FILE NAME
FNAME_Fmk	= 'Fmk.mat';        %%% Fmk - MARKER FILE NAME
FNAME_Re	= 'Re.mat';         %%% Re - ERROR MEASURE Re-VECTOR FILE NAME
FNAME_RANK	= 'RANK.mat';       %%% RANK - RANK OF A-MATRIX MEASURE FILE NAME
FNAME_INVIG	= 'INVIG.mat';      %%% INVERSION INITIAL GUESS VECTOR FILE NAME
FNAME_GRID  = 'DVGRID.mat';     %%% DV GRID FILE FOR MACRO MESH GENERATION
FNAME_MESH  = 'MESHDATA.mat';   %%% MESHDATA FILE FOR MACRO MESH INFORMATION
FNAME_Ksym  = 'Ksym.mat';       %%% SYM BC MATRIX
FNAME_Kfs   = 'Kfs.mat';        %%% FS BC MATRIX
FNAME_Keq   = 'Keq.mat';        %%% EQUILIBRIUM MATRIX
FNAME_KQ    = 'KQ.mat';         %%% K & Q MATRIX - MLS METHOD

%%% SPF INVERSION OPTIONS
frmesh  = load('wshex3x');          %%% WORKSPACE FILE NAME FOR FRMESH
frmesh  = frmesh.wshex3x.frmesh;
nHarm   = 15;                       %%% NUMBER OF HARMONICS

UseProjectedHarmonics	= 1;        %%% USE PROJECTED HARMONICS GENERATED AT FINER FRMESH
UsePreMultiplier        = 1;        %%% USE PRE-MULTIPLIER
Save_recalc_SPF         = 0;        %%% SAVE RECALCULATED SPF
Plot_recalc_SPF         = 0;        %%% PLOT RECALCULATED SPF

fib_div = 1000;     %%% NUMBER OF STEPS ALONG XSTALLOGRAPHIC FIBER
UseA0	= 1;        %%% BUILD DEFAULT INVERSION MATRIX (A0) AND STRIP OUT ROWS - FASTER
SaveA   = 1;        %%% SAVE INVERSION MATRIX FOR EACH DV (A) - SAVES TIME
UseLSDF = 0;        %%% FORMULATION : 1 - (A*X=eqq) GIVES X FOR LSDF, 0 - (A*X=eqq) GIVES X FOR SODF

%%% LIST OF HKLS
hkls	= [
    1 0 0; ...
    0 0 2; ...
    1 0 1; ...
    1 0 2; ...
    1 1 0; ...
    2 0 0; ...
    1 1 2; ...
    2 0 1; ...
    0 0 4; ...
    2 0 2; ...
    1 0 4; ...
    ];
nhkls   = size(hkls, 1);
LatticePrms = [2.9206 4.6685];              %%% NEEDED FOR HCP HKIL <> NORMAL VECTOR CONVERSION

%%% SINGLE XSTAL STIFFNESS (TPa, C11, C33, C12, C13, C44)
C11 = 0.141000;
C33 = 0.163000;
C12 = 0.076900;
C13 = 0.057900;
C44 = 0.048700;                % TPa CAREFUL FOR FACTOR OF TWO!!! SIG_XY = C44 * GAMMA_XY
C   = [C11; C33; C12; C13; 2*C44];
S   = C2S(C, 'Symmetry', 'hexagonal');

C   = BuildElasticityMatrix(C, 'Symmetry', 'hexagonal');
S   = BuildElasticityMatrix(S, 'Symmetry', 'hexagonal');

%%% DIFFRACTION VOLUME INFORMATION
%%% NUMBER OF DIFFRACTION VOLUMES (DVS)
ndv	= 24;       % WE DUPLICATE DVS
%%% X-COODINATES OF DVS
dvx	= [ ...
    0.45 0.45 0.45 0.45 0.45 0.45, 1.35 1.35 1.35 1.35 1.35 1.35, ...
    0.45 0.45 0.45 0.45 0.45 0.45, 1.35 1.35 1.35 1.35 1.35 1.35, ...
    ];
%%% Y-COODINATES OF DVS
dvy	= [ ...
    0.45 0.45 0.45 0.45 0.45 0.45, 0.45 0.45 0.45 0.45 0.45 0.45, ...
    1.35 1.35 1.35 1.35 1.35 1.35, 1.35 1.35 1.35 1.35 1.35 1.35, ...
    ];
%%% Z-COODINATES OF DVS
dvz = [ ...
    0 0.5 1.0 1.5 2.0 2.5, 0 0.5 1.0 1.5 2.0 2.5, ...
    0 0.5 1.0 1.5 2.0 2.5, 0 0.5 1.0 1.5 2.0 2.5, ...
    ] + 0.25;

ODF_OPTION	= 1;        %%% ODF_OPTION : 0 - UNIFORM ODF FOR ALL DVS, 1 - DV_SPECIFIC ODF
%%% LOCAL ODF
% PFNAME_ODF	= { ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\odf_hcp.data'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\odf_hcp.data'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\odf_hcp.data'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\odf_hcp.data'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\odf_hcp.data'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\odf_hcp.data'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\odf_hcp.data'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\odf_hcp.data'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\odf_hcp.data'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\odf_hcp.data'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\odf_hcp.data'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\odf_hcp.data'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\odf_hcp.data'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\odf_hcp.data'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\odf_hcp.data'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\odf_hcp.data'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\odf_hcp.data'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\odf_hcp.data'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\odf_hcp.data'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\odf_hcp.data'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\odf_hcp.data'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\odf_hcp.data'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\odf_hcp.data'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\odf_hcp.data'; ...
%     };
PFNAME_ODF	= { ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/odf_hcp.data'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/odf_hcp.data'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/odf_hcp.data'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/odf_hcp.data'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/odf_hcp.data'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/odf_hcp.data'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/odf_hcp.data'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/odf_hcp.data'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/odf_hcp.data'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/odf_hcp.data'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/odf_hcp.data'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/odf_hcp.data'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/odf_hcp.data'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/odf_hcp.data'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/odf_hcp.data'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/odf_hcp.data'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/odf_hcp.data'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/odf_hcp.data'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/odf_hcp.data'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/odf_hcp.data'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/odf_hcp.data'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/odf_hcp.data'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/odf_hcp.data'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/odf_hcp.data'; ...
    };

%%% ODF CHECK VS. NUMIND IN FRMESH
if ODF_OPTION == 1
    if size(PFNAME_ODF,1) ~= ndv
        error('the number of odfs does not match the number of dvs ...')
    else
        for i = 1:1:ndv
            odf = load(PFNAME_ODF{i,1});
            if size(odf,1) ~= frmesh.numind
                error('odf does not match the number of numind in frmesh ...')
            end
        end
    end
    clear i odf
end

PNAME_LS_DATA_OPTION    = 0;        %%% OPTION : 0 - PATH PROVIDED BELOW FOR EACH DV, 1 - PATH PATTERN SUBMITTED BY USER
%%% LS DATA PATH
% PNAME_LS_DATA	= { ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\dv0-spf'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\dv1-spf'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\dv2-spf'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\dv3-spf'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\dv4-spf'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\dv5-spf'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\dv0-spf'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\dv1-spf'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\dv2-spf'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\dv3-spf'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\dv4-spf'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\dv5-spf'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\dv0-spf'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\dv1-spf'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\dv2-spf'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\dv3-spf'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\dv4-spf'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\dv5-spf'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\dv0-spf'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\dv1-spf'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\dv2-spf'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\dv3-spf'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\dv4-spf'; ...
%     'C:\Users\jspark\Desktop\residual-stress\multiscale-formulation\example\dv5-spf'; ...
%     };
PNAME_LS_DATA	= { ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/dv0-spf'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/dv1-spf'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/dv2-spf'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/dv3-spf'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/dv4-spf'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/dv5-spf'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/dv0-spf'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/dv1-spf'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/dv2-spf'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/dv3-spf'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/dv4-spf'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/dv5-spf'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/dv0-spf'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/dv1-spf'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/dv2-spf'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/dv3-spf'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/dv4-spf'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/dv5-spf'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/dv0-spf'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/dv1-spf'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/dv2-spf'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/dv3-spf'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/dv4-spf'; ...
    '/home/jspark/VBShared/residual-stress/multiscale-formulation/example/dv5-spf'; ...
    };

if ~PNAME_LS_DATA_OPTION
    if size(PNAME_LS_DATA,1) ~= ndv
        error('the number of LS data paths does not match the number of dvs ...')
    end
end
%%% LS DATA FILE NAME COMMON ROOT
%%% THIS ASSUMES THAT SCATTERING VECTOR REMAINS IDENTICAL THROUGHOUT
FNAME_LS_DATA_ROOT  = 'spf_N_7_Phase_2_hkl_';

%%% BCS - NOTE THAT TRACTION MATCHES LOAD NUMBER
%%% NOTE THAT TRACTION UNITS NEED TO BE CONSISTENT WITH SX-C UNITS
%%% XP - POSITIVE-X FACE
%%% XN - NEGATIVE-X FACE
%%% YP - POSITIVE-Y FACE
%%% YN - NEGATIVE-Y FACE
%%% ZP - POSITIVE-Z FACE
%%% ZN - NEGATIVE-Z FACE
% face_xp = [0 0 0];
% face_xn = [0 0 0];
% face_yp = [0 0 0];
% face_yn = [0 0 0];
% face_zp = [0 0 8.1000e-04]; 
% face_zn = [0 0 -8.1000e-04];

SIMGA_APPLIED   = [ ...
    0; ...
    0; ...
    8.1000e-04; ...
    0; ...
    0; ...
    0; ...
    ];

%%% SPF INFORMATION
%%% ETA
neta        = 72;           %%% NUMBER OF ETA
deta        = 360/neta;     %%% ETA STEPS
eta_ini     = -2.5000;      %%% STARTING ETA
eta_fin     = 357.5000;     %%% ENDING ETA
%%% OMEGA
nomega      = 15;           %%% NUMBER OF OMEGA
domega      = 10;           %%% OMEGA STEPS
omega_ini	= -70;          %%% STARTING OMEGA
omega_fin   = 70;           %%% ENDING OMEGA

%%% PENALTY PARAMETERS FOR RESIDUAL STRESS FORMULATION
lambda1 = 100;              %%% Penalty parameter for equilibrium
lambda2 = 10;               %%% Penalty parameter for traction-free surfaces
lambda3 = 10;               %%% Penalty parameter for symmetry surfaces
kappa   = 1.5;              %%% Scaling factor for the ellipsoids

disp('saving input mat file ...')
disp(FNAME_INPUT)
save(FNAME_INPUT)