function edd_show_scan_details(varargin)
% show detail scan information.
%
% Usage: edd_show_scan_details(da[i])
%
%     da[i]: i-th scan struct from readedd5_6bm
%            default i=1
%
% Copyright 2018 Andrew Chuang
% $Revision: 1.0 $  $Date: 2018/02/07 $

heddshowscanMain = findall(0,'Tag','eddshowscanmain_Fig');
if isempty(heddshowscanMain)
    switch nargin
        case 1
            da = varargin{1}(1);
        otherwise
            fprintf('Usage: edd_show_scan_details(data_struct)\n')
            return;
    end
        
    initFigure(da);

else
    switch nargin
        case 1
            da = varargin{1}(1);
        otherwise
            fprintf('Usage: edd_show_scan_details(data_struct)\n')
            return;
    end    
    figure(heddshowscanMain);
    h = get_handle;
    mtab = h.showscan_table;
    % update number based on input
    h.showscanmain_text_WB.String = sprintf('WB: %4d x %4d',...
             round((da.allmotors.ush-da.allmotors.dsh)*1000),...
             round((da.allmotors.usv-da.allmotors.dsv)*1000));
    h.showscanmain_text_S1.String = sprintf('S1: %4d x %4d',...
             round((da.allmotors.s1out-da.allmotors.s1in)*1000),...
             round((da.allmotors.s1top-da.allmotors.s1bot)*1000));
    h.showscanmain_text_S2.String = sprintf('S2: %4d x %4d',...
             round((da.allmotors.s2out-da.allmotors.s2in)*1000),...
             round((da.allmotors.s2top-da.allmotors.s2bot)*1000));
    h.showscanmain_text_S4v.String = sprintf('S4v: %4d x %4d',...
             round((da.allmotors.s4vout-da.allmotors.s4vin)*1000),...
             round((da.allmotors.s4vtop-da.allmotors.s4vbot)*1000));
    h.showscanmain_text_S4h.String = sprintf('S4h: %4d x %4d',...
             round((da.allmotors.s4hout-da.allmotors.s4hin)*1000),...
             round((da.allmotors.s4htop-da.allmotors.s4hbot)*1000));
    h.showscanmain_text_vtth.String = sprintf('2%cv: %1.4f', 952,...
             abs(da.allmotors.vtth));
    h.showscanmain_text_htth.String = sprintf('2%ch: %1.4f', 952,...
             abs(da.allmotors.htth));
    set(mtab,'Data',num2cell(da.motorpos_all));    
    set(mtab,'ColumnName',da.motornames);
    update_handle(h)
end

%================================================================
% --- initialize main figure layout
%================================================================
function initFigure(da)
% --------------------------------
% --- main figure handle
% --------------------------------
pos = get(0,'PointerLocation');
figureSize = [555 205];
figurePos  = [pos(1) pos(2)-180 figureSize];
tablesize = 125;
row1 = tablesize+12;
row2 = tablesize+39;
heddshowscanmain = figure(...
    'BackingStore','on',...
    'Units','pixels',...
    'DockControls','off',...
    'Resize','off',...
    'PaperOrient','portrait',...
    'PaperPositionMode','auto',...
    'IntegerHandle','off',...
    'NumberTitle','off',...
    'MenuBar','none',...
    'Toolbar','none',...
    'Name','Detail Motor Positions',...
    'Position',figurePos,...
    'HandleVisibility','callback',...
    'Tag','eddshowscanmain_Fig',...
    'CloseRequestFcn',@eddshowscanmain_CloseRequestFcn,...
    'UserData',[]);
hAxes = axes(...
    'Parent',heddshowscanmain,...
    'Units','pixels',...
    'Position',[0 0 figureSize],...
    'Xlim',[0 figureSize(1)],...
    'Ylim',[0 figureSize(2)],...
    'Tag','eddshowscanmain_Axes');
hPatchMain = patch(...
    'Parent',hAxes,...
    'XData',[0 figureSize(1) figureSize(1) 0],...
    'YData',[0 0 figureSize(2) figureSize(2)],...
    'FaceColor',[1 1 0.55],...
    'EdgeColor',[1 1 0.55]);

% ----------------------------------------
% --- layout of control panel putshbuttons
% ----------------------------------------
text('Parent',hAxes,...
    'Position',[10 row1+12],...
    'String','(h x v) in \mum',...
    'Fontsize',13,...
    'Units','pixel',...
    'HorizontalAlignment','left',...
    'Color',[0.4 0.3 0]);

htext(1) = uicontrol('Style','text',...
    'Parent',heddshowscanmain,...
    'units','pixels',...
    'Position',[10 row2-5 140 25],...
    'backgroundcolor',[1 1 0.55],...
    'fontsize',12,...
    'String',sprintf('WB: %4d x %4d',...
             round((da.allmotors.ush-da.allmotors.dsh)*1000),...
             round((da.allmotors.usv-da.allmotors.dsv)*1000)),...
    'HorizontalAlignment','left',...
    'Enable','on',...
    'Tag','showscanmain_text_WB');

htext(2) = uicontrol('Style','text',...
    'Parent',heddshowscanmain,...
    'units','pixels',...
    'Position',[155 row2-5 135 25],...
    'backgroundcolor',[0.75 1 0.75],...
    'fontsize',12,...
    'String',sprintf('S1: %4d x %4d',...
             round((da.allmotors.s1out-da.allmotors.s1in)*1000),...
             round((da.allmotors.s1top-da.allmotors.s1bot)*1000)),...
    'HorizontalAlignment','left',...
    'Enable','on',...
    'Tag','showscanmain_text_S1');

htext(3) = uicontrol('Style','text',...
    'Parent',heddshowscanmain,...
    'units','pixels',...
    'Position',[155 row1-5 135 25],...
    'backgroundcolor',[1 1 0.55],...
    'fontsize',12,...
    'String',sprintf('S2: %4d x %4d',...
             round((da.allmotors.s2out-da.allmotors.s2in)*1000),...
             round((da.allmotors.s2top-da.allmotors.s2bot)*1000)),...
    'HorizontalAlignment','left',...
    'Enable','on',...
    'Tag','showscanmain_text_S2');

htext(4) = uicontrol('Style','text',...
    'Parent',heddshowscanmain,...
    'units','pixels',...
    'Position',[295 row2-5 145 25],...
    'backgroundcolor',[1 1 0.55],...
    'fontsize',12,...
    'String',sprintf('S4v: %4d x %4d',...
             round((da.allmotors.s4vout-da.allmotors.s4vin)*1000),...
             round((da.allmotors.s4vtop-da.allmotors.s4vbot)*1000)),...
    'HorizontalAlignment','left',...
    'Enable','on',...
    'Tag','showscanmain_text_S4v');

htext(5) = uicontrol('Style','text',...
    'Parent',heddshowscanmain,...
    'units','pixels',...
    'Position',[295 row1-5 145 25],...
    'backgroundcolor',[1 1 0.55],...
    'fontsize',12,...
    'String',sprintf('S4h: %4d x %4d',...
             round((da.allmotors.s4hout-da.allmotors.s4hin)*1000),...
             round((da.allmotors.s4htop-da.allmotors.s4hbot)*1000)),...
    'HorizontalAlignment','left',...
    'Enable','on',...
    'Tag','showscanmain_text_S4h');

htext(6) = uicontrol('Style','text',...
    'Parent',heddshowscanmain,...
    'units','pixels',...
    'Position',[445 row2-5 105 25],...
    'backgroundcolor',[1 0.75 0.55],...
    'fontsize',12,...
    'String',sprintf('2%cv: %1.4f',...
             952,...
             abs(da.allmotors.vtth)),...
    'HorizontalAlignment','left',...
    'Enable','on',...
    'Tag','showscanmain_text_vtth');

htext(7) = uicontrol('Style','text',...
    'Parent',heddshowscanmain,...
    'units','pixels',...
    'Position',[445 row1-5 105 25],...
    'backgroundcolor',[1 0.75 0.55],...
    'fontsize',12,...
    'String',sprintf('2%ch: %1.4f',...
             952,...
             da.allmotors.htth),...
    'HorizontalAlignment','left',...
    'Enable','on',...
    'Tag','showscanmain_text_htth');

% construct table
data = num2cell(da.motorpos_all);

htablepar = uitable('Parent',heddshowscanmain,...
    'Units','pixels',...
    'Position',[10 10 figureSize(1)-20 tablesize],...
    'ColumnName',da.motornames,...
    'ColumnEditable',false(zeros(1,length(da.motornames))),...
    'Data',data,...
    'Fontsize',11,...
    'CellSelectionCallback',@uitable_selection_Callback,...
    'Tag','showscan_table');

allhandle = guihandles(heddshowscanmain);
update_handle(allhandle)

%==========================================================================
% --- Callbacks for  
%==========================================================================

%%%% call back to report selection
function uitable_selection_Callback(~,eventdata,~)
%    h = get_handle;
    eventdata.Indices
%    h.opt.table_selection = eventdata.Indices;
%    update_handle(h);


%==========================================================================
% --- close request function of eddshowscanmain fig 
%==========================================================================
function eddshowscanmain_CloseRequestFcn(hObject,eventdata)                
    delete(findall(0,'Tag','eddshowscanmain_Fig'))
    delete(findall(0,'-regexp','Tag','eddgetpar*'))  

%==========================================================================
% --- Load all handle object function
%==========================================================================
function h = get_handle
    hmain = findall(0,'Tag','eddshowscanmain_Fig');
    h = getappdata(hmain,'allhandle');

%==========================================================================
% --- Save all handle object function
%==========================================================================
function update_handle(handle_to_save)
    hmain = findall(0,'Tag','eddshowscanmain_Fig');
    setappdata(hmain,'allhandle',handle_to_save);