function h = PlotSpcFit(xData, yData, yCalc0, yCalc)
h   = figure;
set(h, 'Position', [43 484 1211 438]);

plot(xData, yData, ...
    'LineStyle', 'none', ...
    'Marker', 's', ...
    'MarkerSize', 7, ...
    'MarkerEdgeColor', 'k', ...
    'MarkerFaceColor', 'k')

hold on

plot(xData, yCalc0, ...
    'LineStyle', '-.', ...
    'LineWidth', 2, ...
    'Color', 'k', ...
    'Marker', 'none')
    
plot(xData, yCalc, ...
    'LineStyle', '-', ...
    'LineWidth', 2, ...
    'Color', 'k', ...
    'Marker', 'none')

dy  = (yData - yCalc)./yCalc;

ylabel('Intensity (arb. units)', 'FontSize', 16, 'FontWeight', 'bold')
legend({'Data', 'Ini Guess', 'Fit'}, 'Location', 'Best')

h1  = gca;
set(h1, 'FontSize', 16, ...
    'FontWeight', 'bold', ...
    'Position', [0.07 0.36 0.90 0.60])
axis tight

h2  = axes;
plot(xData, dy, ...
    'LineStyle', '-', ...
    'LineWidth', 2, ...
    'Color', 'k', ...
    'Marker', 'none')
xlabel('2\theta (deg)', 'FontSize', 16, 'FontWeight', 'bold')
ylabel('y_{data} - y_{fit} / y_{data}', 'FontSize', 16, 'FontWeight', 'bold')
set(h2, 'FontSize', 16, ...
    'FontWeight', 'bold', ...
    'Position', [0.07 0.10 0.90 0.18])
axis tight