function [] = PlotSpcFit2D(etaData, xData, yData, yCalc0, yCalc)
% save('mfiles\test-mats\PlotSpcFit2D.test.mat')
% return
% clear all
% close all
% clc
% load('mfiles\test-mats\PlotSpcFit2D.test.mat')

diff    = (yCalc - yData)./yData;

cmax    = max([max(max(yData)) max(max(yCalc0)) max(max(yCalc)) max(max(diff))]);
cmin    = min([min(min(yData)) min(min(yCalc0)) min(min(yCalc)) min(min(diff))]);
clim    = [cmin cmax];

nxData  = length(xData);
XTick   = round(linspace(1,nxData,4));
XTickLabel  = round(xData(XTick)*10)/10;

netaData    = length(etaData);
YTick       = round(linspace(1,netaData,4));
YTickLabel  = round(etaData(YTick)*10)/10;

subplot(2,2,1)
imagesc(yData)
set(gca, 'FontSize', 16, ...
    'FontWeight', 'bold', ...
    'XTick', XTick, ...
    'XTickLabel', XTickLabel, ...
    'YTick', YTick, ...
    'YTickLabel', YTickLabel)
xlabel('2\theta (deg)')
ylabel('\eta (deg)')
caxis(clim)
set(colorbar, ...
    'YLim', clim, ...
    'FontSize', 14, ...
    'FontWeight', 'bold', ...
    'Location', 'EastOutside')

subplot(2,2,2)
imagesc(yCalc0)
set(gca, 'FontSize', 16, ...
    'FontWeight', 'bold', ...
    'XTick', XTick, ...
    'XTickLabel', XTickLabel, ...
    'YTick', YTick, ...
    'YTickLabel', YTickLabel)
xlabel('2\theta (deg)')
ylabel('\eta (deg)')
caxis(clim)
set(colorbar, ...
    'YLim', clim, ...
    'FontSize', 14, ...
    'FontWeight', 'bold', ...
    'Location', 'EastOutside')

subplot(2,2,3)
imagesc(yCalc)
set(gca, 'FontSize', 16, ...
    'FontWeight', 'bold', ...
    'XTick', XTick, ...
    'XTickLabel', XTickLabel, ...
    'YTick', YTick, ...
    'YTickLabel', YTickLabel)
xlabel('2\theta (deg)')
ylabel('\eta (deg)')
caxis(clim)
set(colorbar, ...
    'YLim', clim, ...
    'FontSize', 14, ...
    'FontWeight', 'bold', ...
    'Location', 'EastOutside')

clim    = [-.25 .25];
subplot(2,2,4)
imagesc(diff)
set(gca, 'FontSize', 16, ...
    'FontWeight', 'bold', ...
    'XTick', XTick, ...
    'XTickLabel', XTickLabel, ...
    'YTick', YTick, ...
    'YTickLabel', YTickLabel)
xlabel('2\theta (deg)')
ylabel('\eta (deg)')
caxis(clim)
set(colorbar, ...
    'YLim', clim, ...
    'FontSize', 14, ...
    'FontWeight', 'bold', ...
    'Location', 'EastOutside')