function t = MatrixOfStressStrainInVM(v)
v   = v(:);
if (size(v,1) == 6)
    s2  = sqrt(2);
    t   = [ ...
        v(1)    v(4)/s2 v(5)/s2; ...
        v(4)/s2    v(2) v(6)/s2; ...
        v(5)/s2 v(6)/s2 v(3); ...
        ];
else
    disp('input vector size incorrect');
end