function v = VecOfStressStrainInVM(t)

if (size(t,1) == 3) && (size(t,2) == 3)
    s2  = sqrt(2);
    v   = [ ...
        t(1,1); ...
        t(2,2); ...
        t(3,3); ...
        s2*t(1,2); ...
        s2*t(1,3); ...
        s2*t(2,3); ...
        ];
else
    disp('input matrix size incorrect');
end