function t = VectorOfStressStrainMatrixInVM(v, varargin)
% MatrixOfStressStrainInVM - Converts vectorized stress (strain) to a
% matrix
%
%   USAGE:
%
%   t = MatrixOfStressStrainInVM(v)
%
%   INPUT:
%
%   v
%       modified Voight-Mandel stress (strain) vector in [11, 22, 33, 12,
%       13, 23] order. Shears are expected to have factor of sqrt(2)
%       multiplied to them already.
%
%   t
%       stress (strain) matrix.

% default options
optcell = {...
    'Order', '11-22-33-23-13-12', ...
    };

% update option
opts    = OptArgs(optcell, varargin);

if (size(v,1) == 3) && (size(v,2) == 3)
    s2  = sqrt(2);
    if strcmp(opts.Order, '11-22-33-23-13-12')
        t   = [ ...
            v(1,1); ...
            v(2,2); ...
            v(3,3); ...
            s2*v(2,3); ...
            s2*v(1,3); ...
            s2*v(1,2); ...
            ];
    elseif strcmp(opts.Order, '11-22-33-12-13-23')
        t   = [ ...
            v(1,1); ...
            v(2,2); ...
            v(3,3); ...
            s2*v(1,2); ...
            s2*v(1,3); ...
            s2*v(2,3); ...
            ];
    else
        disp('order not supported');
        return
    end
else
    disp('input matrix size incorrect');
end