function fout = ApplyGeometricModel(p, params)
centers             = [p(1) p(2)]./1000;
distance            = p(3);
gX                  = p(4);
gY                  = p(5);

pkidx           = params.pkidx;
tth             = params.tth;
azim            = params.azim;
dettype         = params.dettype;
rho             = params.rho;
find_detpars    = params.find_detpars;
DistortParams0  = params.DistortParams0;

if find_detpars
    DistortionParams    = p(6:end);
else
    DistortionParams    = DistortParams0;
end

tth = tth(pkidx);
if strcmp(dettype,'0')
    mapped_tth  = GeometricModelXRD0(...
        centers, ...
        distance, ...
        gY, gX, ...
        rho, azim);
elseif strcmp(dettype,'1')
    mapped_tth  = GeometricModelXRD1(...
        centers, ...
        distance, ...
        gY, gX, ...
        rho, azim, DistortionParams);
elseif strcmp(dettype,'2')
    mapped_tth  = GeometricModelXRD2(...
        centers, ...
        distance, ...
        gY, gX, ...
        rho, azim, DistortionParams);
elseif strcmp(dettype,'2a')
    mapped_tth  = GeometricModelXRD2a(...
        centers, ...
        distance, ...
        gY, gX, ...
        rho, azim, DistortionParams);
elseif strcmp(dettype,'2b')
    mapped_tth  = GeometricModelXRD2b(...
        centers, ...
        distance, ...
        gY, gX, ...
        rho, azim, DistortionParams);
end
tth     = repmat(tth,size(mapped_tth,2),1)';
fout    = tth - mapped_tth;
