function Rvec = AxialVectorCOB(Rmat)

dim3 = size(Rmat, 3);
Rvec = zeros(3, 3, dim3);
for i = 1:dim3
    Rvec(1, :, i) = [Rmat(2, 2, i)*Rmat(3, 3, i) - Rmat(2, 3, i)*Rmat(3, 2, i), ...
                     Rmat(2, 3, i)*Rmat(3, 1, i) - Rmat(2, 1, i)*Rmat(3, 3, i), ...
                     Rmat(2, 1, i)*Rmat(3, 2, i) - Rmat(2, 2, i)*Rmat(3, 1, i), ...
                    ];
    Rvec(2, :, i) = [Rmat(1, 3, i)*Rmat(3, 2, i) - Rmat(1, 2, i)*Rmat(3, 3, i), ...
                     Rmat(1, 1, i)*Rmat(3, 3, i) - Rmat(1, 3, i)*Rmat(3, 1, i), ...
                     Rmat(1, 2, i)*Rmat(3, 1, i) - Rmat(1, 1, i)*Rmat(3, 2, i), ...
                    ];
    Rvec(3, :, i) = [Rmat(1, 2, i)*Rmat(2, 3, i) - Rmat(1, 3, i)*Rmat(2, 2, i), ...
                     Rmat(1, 3, i)*Rmat(2, 1, i) - Rmat(1, 1, i)*Rmat(2, 3, i), ...
                     Rmat(1, 1, i)*Rmat(2, 2, i) - Rmat(1, 2, i)*Rmat(2, 1, i), ...
                    ];
end
