clear all
close all
clc

p1  = [ 50; 0.15; 0.23; 0.5; 0.7; 5.00];
p1  = p1(:);

p2  = [ 125; 0.15; 0.7; 4.30];
p2  = p2(:);

x       = 4:0.01:6;

xdata   = x(:);
ydata1  = pksplitpseudoVoigt(p1, x);
ydata2  = pkpseudoVoigt(p2, x);

ydata   = ydata1 + ydata2 + -1.5 + 20.*rand(length(x),1);

%%%%%%%%%%%%%%%%%%%%%%
% pars.pfunc_type = 'splitpseudovoigt';
% pars.pbkg_order = 2;
% pars.xdata      = xdata;
% 
% p0  = [ ...
%     70; ...
%     0.25; ...
%     0.23; ...
%     0.8; ...
%     0.5; ...
%     5.00; ...
%     0; ...
%     10; ...
%     ];
%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%
pars.pfunc_type = 'pseudovoigt';
pars.pbkg_order = 2;
pars.xdata      = xdata;

p0  = [ ...
    70; ...
    0.25; ...
    0.23; ...
    4.9; ...
    100; ...
    0.25; ...
    0.23; ...
    4.2; ...
    0.5; ...
    0.00; ...
    ];
%%%%%%%%%%%%%%%%%%%%%%

[pr, rsn, ~, ef]    = lsqcurvefit(@pfunc_switch, p0, pars, ydata);

yfit0   = pfunc_switch(p0, pars);
yfit	= pfunc_switch(pr, pars);

figure,
plot(xdata, ydata, 'ro')
hold on
plot(xdata, yfit0, 'g:')
plot(xdata, yfit, 'b-')