clear all
close all
clc

p   = [
    50; ...
    0.15; ...
    0.23; ...
    0.5; ...
    0.7; ...
    5.00];
x   = 4:0.01:6;
p   = p(:);

xdata   = x(:);
ydata   = pksplitpseudoVoigt(p, x);
ydata   = ydata + -1.5 + (3).*rand(length(x),1);

p0  = [ ...
    70; ...
    0.25; ...
    0.23; ...
    0.8; ...
    0.5; ...
    5.00; ...
    0; ...
    10; ...
    ];

pars.pfunc_type = 'splitpseudovoigt';
pars.pbkg_order = 2;
pars.xdata      = xdata;

[pr, rsn, ~, ef]    = lsqcurvefit(@pfunc_switch, p0, pars, ydata);

yfit0   = pfunc_switch(p0, pars);
yfit	= pfunc_switch(pr, pars);

figure,
plot(xdata, ydata, 'ro')
hold on
plot(xdata, yfit0, 'g:')
plot(xdata, yfit, 'b-')